### PR TITLE
WIP: major clean ups for the codebase

### PR DESCRIPTION
**Pull request by hozan23**

### CODE REVIEW

**Comment by lemonyte** [comment]
I see the majority of the changes are adding `Union[<type>, None]` type hints for parameters. The recommended way to type hint this is to use [typing.Optional](https://docs.python.org/3/library/typing.html#typing.Optional), which is basically an alias for `Union[<type>, None]`. Also, a lot of the changes are duplicated in #69, perhaps it would be best to review that PR and see what could be merged there?

**Comment by hozan23** [comment]
> I see the majority of the changes are adding Union[<type>, None] type hints for parameters. The recommended way to type hint this is to use typing.Optional, which is basically an alias for Union[<type>, None]. Also, a lot of the changes are duplicated in #69, perhaps it would be best to review that PR and see what could be merged there?

I am not sure about the ideal way of using typing hints in Python. I think `Union` and `Optional` are equivalent. In the future, we will use `type | None` instead of both. Also, in my opinion, `Union` is more like the new typing hint.

**Comment by pomdtr** [comment]
> I am not sure about the ideal way of using typing hints in Python. I think Union and Optional are equivalent. In the future, we will use type | None instead of both. Also, in my opinion, Union is more like the new typing hint.

Optional is the way to go. They are virtually equivalent (see https://peps.python.org/pep-0645/), but optional is a more readable way to express the same thing.

**Review by aavshr — APPROVED** [review]

**Comment by cclauss** [comment]
It is probably better to fix the [failing tests](https://github.com/deta/deta-python/actions) BEFORE merging more pull requests.

**Comment by hozan23** [comment]
Hey @cclauss thanks for your advice.

**Pull request merged**
